#!/bin/bash
###############################################################################
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
# Build cpu dependencies.

if [ -z "$BASH_VERSION" ]
then
  echo "This script must be run under bash"
  exit 1
fi

# Do not set Exit on Error in scripts that will be sourced
# set -o errexit

SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"

# Read command line options
. "${SCRIPT_DIR}/_buildopts.sh" \
    --name bootstrap \
    --desc "Build cpu dependencies." \
    -- "$@"

python3 "${SCRIPT_DIR}/bootstrap.py" ${FORWARD_OPTS}
