#!/bin/bash
###############################################################################
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
# Build cpu.

set -o errexit


SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"

# Read command line options
. "${SCRIPT_DIR}/_buildopts.sh" \
    --name build \
    --desc "Build cpu." \
    -- "$@"

# Load project environment
if [ -z "${VPL_ROOT}" ]; then
  echo "Environment script appears not to have been run."
  echo "Attempting to run now..."

  if [ ! -e "${VPL_INSTALL_DIR}" ]
  then
    echo "Base must be installed to build implementation"
    exit 1
  fi

  if [ ! -e "${VPL_INSTALL_DIR}/env/vars.sh" ]
  then
    # Detect case where user points VPL_INSTALL_DIR at the
    # Base repo instead of the built output.
    echo "Cannot find environment script in ${VPL_INSTALL_DIR}/env"
    exit 1
  fi

  source "${VPL_INSTALL_DIR}/env/vars.sh"
else
  echo "Environment script appears to have already run. Continuing..."
fi

if [ -n "${BOOTSTRAP_OPT}" ]
then
  echo "Building dependencies..."
  "${SCRIPT_DIR}/bootstrap" ${FORWARD_OPTS}
fi

if [ -n "${VPL_INSTALL_DIR}" ]
then
  mkdir -p "${VPL_INSTALL_DIR}"
  INSTALL_PREFIX_CM_OPT="-DCMAKE_INSTALL_PREFIX=${VPL_INSTALL_DIR}"
fi

COFIG_CM_OPT="-DCMAKE_BUILD_TYPE=${COFIG_OPT}"

pushd "${PROJ_DIR}"
  BUILD_DIR=_build
  if [ "${GPL_OPT}" == "yes" ]; then
    CMAKE_GPL_OPT=-DBUILD_GPL_X264=ON
  fi
  mkdir -p ${BUILD_DIR}
  pushd "${BUILD_DIR}"
    cmake "${INSTALL_PREFIX_CM_OPT}" ${CMAKE_GPL_OPT} "${COFIG_CM_OPT}" ..
    make -j "$(nproc)" VERBOSE=1
    cmake --build . --config "${COFIG_OPT}" --target package
  popd
popd

# Signal to CI system 
if [ -n "${TEAMCITY_VERSION}" ]; then
  echo "##teamcity[publishArtifacts 'oneVPL-cpu/${BUILD_DIR}/*-all.zip=>']"
fi
