#!/bin/bash
###############################################################################
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
## start of boilerplate to switch to project root ------------------------------
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
proj_dir="$( dirname "${script_dir}" )"
cd ${proj_dir}
##set -o errexit

## Read options -----------------------------------------------------------
export USE_GPL="no"
export BUILD_MODE= "Release"

while [ "$1" != "" ]; do
    case $1 in
        gpl )
            export USE_GPL="yes"
            ;;
        debug )
            export BUILD_MODE="Debug"
            ;;
        * )
            echo "usage: build [gpl] [debug]"
            exit 1
    esac
    shift
done

## start of commands -----------------------------------------------------------
## capture ci errors that should not block the rest of the chain
ci_error=0

script/lint
if [ $? -ne 0 ];then
    echo "--- Linting FAILED ---"
    ci_error=1
fi

if [ -z "$VPL_BUILD_DEPENDENCIES" ];then
    if [ "${USE_GPL}" == "yes" ]; then
      source script/bootstrap gpl debug
    else
      source script/bootstrap
    fi
    if [ $? -ne 0 ];then
        echo "--- Bootstrapping FAILED---"
        exit 1
    fi
fi

if [ "${USE_GPL}" == "yes" ]; then
  if [ "${BUILD_MODE}" == "Debug" ]; then
    source script/package gpl debug
  else
    source script/package gpl
  fi
else
  if [ "${BUILD_MODE}" == "Debug" ]; then
    source script/package debug
  else
    source script/package
  fi
fi
if [ $? -ne 0 ];then
    echo "--- Packaging FAILED---"
    exit 1
fi


# run smoke tests
${proj_dir}/script/test
if [ $? -ne 0 ];then
    echo "--- Smoke Tests FAILED ---"
    ci_error=1
fi

if [ $ci_error -ne 0 ]; then
    echo "--- CI testing FAILED ---"
    exit 1
else
    echo "---All Tests PASSED ---"
    exit 0
fi

