#!/bin/bash
###############################################################################
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
# Install cpu.

set -o errexit


SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"

# Read command line options
. "${SCRIPT_DIR}/_buildopts.sh" \
    --name install \
    --desc "Install cpu." \
    -- "$@"

# Load project environment
if [ -z "${VPL_ROOT}" ]; then
  echo "Environment script appears not to have been run."
  echo "Attempting to run now..."

  if [ ! -e "${VPL_INSTALL_DIR}" ]
  then
    echo "Project must be installed to test implementation"
    exit 1
  fi

  if [ ! -e "${VPL_INSTALL_DIR}/env/vars.sh" ]
  then
    # Detect case where user points VPL_INSTALL_DIR at the
    # Base repo instead of the built output.
    echo "Cannot find environment script in ${VPL_INSTALL_DIR}/env"
    exit 1
  fi

  source "${VPL_INSTALL_DIR}/env/vars.sh"
else
  echo "Environment script appears to have already run. Continuing..."
fi

pushd "${PROJ_DIR}"
    BUILD_DIR=_build
    cmake --build "${BUILD_DIR}" --config "${COFIG_OPT}" --target install
popd
