#!/bin/bash
###############################################################################
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
# Install cpu.

if [ "$0" = "$BASH_SOURCE" ]
then
  set -o errexit
else
  echo "Warning: This script should not be sourced. Skipping exit on error."
fi


SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"

# Read command line options
. "${SCRIPT_DIR}/_buildopts.sh" \
    --name install \
    --desc "Install cpu." \
    -- "$@"

###############################################################################
# Globals
if [ -z "${VPL_CPU_BUILD_DIR}" ]
then
  VPL_CPU_BUILD_DIR="${PROJ_DIR}/_build"
fi
###############################################################################

BUILD_DIR="${VPL_CPU_BUILD_DIR}"
cmake --build "${BUILD_DIR}" --config "${COFIG_OPT}" --target install
