#!/bin/bash
###############################################################################
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
## start of boilerplate to switch to project root ------------------------------
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
proj_dir="$( dirname "${script_dir}" )"
cd ${proj_dir}
set -o errexit
## start of commands -----------------------------------------------------------
source ${proj_dir}/test/tools/env/vars.sh
if [ -n "$VPL_BUILD_DEPENDENCIES" ]; then
    export ffmpeg_dir=${VPL_BUILD_DEPENDENCIES}/bin
else
    echo "VPL_BUILD_DEPENDENCIES not defined. Did you run bootstrap?"
    exit 1
fi
export PATH=${ffmpeg_dir}:${PATH}

if [ -n "$VPL_INSTALL_DIR" ]; then
  if [ -z "$VPL_ROOT" ]; then
    source "$VPL_INSTALL_DIR/env/vars.sh"
  fi
fi

cd _build
export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
result_all=0

echo --- Running Unit Tests ---
./vpl-utest --gtest_output=xml:${proj_dir}/_logs/
ret=$?
if [ $ret -ne 0 ]; then
    echo --- Unit Tests FAILED ---
    let result_all++
else
    echo --- Unit Tests PASSED ---
fi

exit $result_all
